Document: python-bufr
Title: Debian python-bufr Manual
Author: <insert document author here>
Abstract: This manual describes what python-bufr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-bufr/python-bufr.sgml.gz

Format: postscript
Files: /usr/share/doc/python-bufr/python-bufr.ps.gz

Format: text
Files: /usr/share/doc/python-bufr/python-bufr.text.gz

Format: HTML
Index: /usr/share/doc/python-bufr/html/index.html
Files: /usr/share/doc/python-bufr/html/*.html

  
