Document: python-bufr-metadb
Title: Debian python-bufr-metadb Manual
Author: <insert document author here>
Abstract: This manual describes what python-bufr-metadb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-bufr-metadb/python-bufr-metadb.sgml.gz

Format: postscript
Files: /usr/share/doc/python-bufr-metadb/python-bufr-metadb.ps.gz

Format: text
Files: /usr/share/doc/python-bufr-metadb/python-bufr-metadb.text.gz

Format: HTML
Index: /usr/share/doc/python-bufr-metadb/html/index.html
Files: /usr/share/doc/python-bufr-metadb/html/*.html

  
