Document: pybufr-metadb
Title: Debian pybufr-metadb Manual
Author: <insert document author here>
Abstract: This manual describes what pybufr-metadb is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pybufr-metadb/pybufr-metadb.sgml.gz

Format: postscript
Files: /usr/share/doc/pybufr-metadb/pybufr-metadb.ps.gz

Format: text
Files: /usr/share/doc/pybufr-metadb/pybufr-metadb.text.gz

Format: HTML
Index: /usr/share/doc/pybufr-metadb/html/index.html
Files: /usr/share/doc/pybufr-metadb/html/*.html

  
