Document: python-sqlalchemy-marshall
Title: Debian python-sqlalchemy-marshall Manual
Author: <insert document author here>
Abstract: This manual describes what python-sqlalchemy-marshall is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-sqlalchemy-marshall/python-sqlalchemy-marshall.sgml.gz

Format: postscript
Files: /usr/share/doc/python-sqlalchemy-marshall/python-sqlalchemy-marshall.ps.gz

Format: text
Files: /usr/share/doc/python-sqlalchemy-marshall/python-sqlalchemy-marshall.text.gz

Format: HTML
Index: /usr/share/doc/python-sqlalchemy-marshall/html/index.html
Files: /usr/share/doc/python-sqlalchemy-marshall/html/*.html

  
