Document: pybufr-transform
Title: Debian pybufr-transform Manual
Author: <insert document author here>
Abstract: This manual describes what pybufr-transform is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pybufr-transform/pybufr-transform.sgml.gz

Format: postscript
Files: /usr/share/doc/pybufr-transform/pybufr-transform.ps.gz

Format: text
Files: /usr/share/doc/pybufr-transform/pybufr-transform.text.gz

Format: HTML
Index: /usr/share/doc/pybufr-transform/html/index.html
Files: /usr/share/doc/pybufr-transform/html/*.html

  
