Document: pybufr
Title: Debian pybufr Manual
Author: <insert document author here>
Abstract: This manual describes what pybufr is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pybufr/pybufr.sgml.gz

Format: postscript
Files: /usr/share/doc/pybufr/pybufr.ps.gz

Format: text
Files: /usr/share/doc/pybufr/pybufr.text.gz

Format: HTML
Index: /usr/share/doc/pybufr/html/index.html
Files: /usr/share/doc/pybufr/html/*.html

  
