Document: python-xml-marshall
Title: Debian python-xml-marshall Manual
Author: <insert document author here>
Abstract: This manual describes what python-xml-marshall is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/python-xml-marshall/python-xml-marshall.sgml.gz

Format: postscript
Files: /usr/share/doc/python-xml-marshall/python-xml-marshall.ps.gz

Format: text
Files: /usr/share/doc/python-xml-marshall/python-xml-marshall.text.gz

Format: HTML
Index: /usr/share/doc/python-xml-marshall/html/index.html
Files: /usr/share/doc/python-xml-marshall/html/*.html

  
